### ISSUE TITLE
cannot add hardware, param fields missing (Domoticz Version: 3.6587)

### ISSUE THREAD

**Issue by thomas-villagers** [tester22/Domoticz-Sonos#2]
Hi tester22, 

when I try to add a Sonos Player, somehow the param fields (address etc.) are missing and I thus cannot add the device: 

![hardware](https://cloud.githubusercontent.com/assets/1818737/22559323/04fbde38-e971-11e6-9516-2a016adcef2f.png)

Might be an issue with the python plugins system and not directly related to your Sonos Plugin (I'll try some other simple generic python plugin when I find the time), but maybe you can give me a hint :-) 

thank you!

**Comment by tester22** [comment]
Not an bug in this plugin :)

**Comment by thomas-villagers** [comment]
yeah :-) I tried a few hours later, different browser and now it works!
