### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by leecollings** [tester22/Domoticz-Sonos#4]
So I've done what the Readme says, copied the files to the folder /plugins/Sonos/

However, nothing new is appearing int he Hardware list. I'm running the latest Beta, and also have checked 'Allow new hardware devices'.

But still the list shows nothing about Sonos. Am I missing something?

**Comment by tester22** [comment]
Not an bug in this plugin :)

**Comment by leecollings** [comment]
Erm, sorry, but I don't accept your canned response and just closing the bug.

Are you not even going to try and help me out... seriously?

**Comment by tester22** [comment]
No dependencies at all.
Follow instructions here: https://www.domoticz.com/forum/viewforum.php?f=65
Have worked for alot of other people.

**Comment by leecollings** [comment]
Wow, I'm stunned by your rudeness. Ciao.
